# Generated by Django 4.2.7 on 2023-11-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_años_radicando_user_calle_numero_user_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='antiguedad_laboral_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='conyuge_pareja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referencia_personal_conyuge_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referencia_personal_conyuge_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_ref_conyuge_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_ref_conyuge_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trabajo_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
