# Generated by Django 4.2.7 on 2023-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo_tiempo', models.CharField(blank=True, max_length=100, null=True)),
                ('interes_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Plazo',
                'verbose_name_plural': 'Plazos',
            },
        ),
    ]
