# Generated by Django 4.2.7 on 2023-11-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_plazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plazo_nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre_plazo', to='dashboard.plazo')),
                ('tipo_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_credito', to='dashboard.productos')),
            ],
            options={
                'verbose_name': 'Simulador',
                'verbose_name_plural': 'Simuladores',
            },
        ),
    ]
